In [2]:
import requests
import pandas as pd
import numpy as np
from gprofiler import GProfiler
from collections import defaultdict
from typing import List, Dict
import spacy
import xml.etree.ElementTree as ET
import re
nlp = spacy.load("en_core_web_sm")

In [3]:
API_URL = "https://api.platform.opentargets.org/api/v4/graphql"
DISEASE_ID = "MONDO_0005180"
query = f"""
query {{
  disease(efoId: "{DISEASE_ID}") {{
    associatedTargets(page: {{ index: 0, size: 100 }}) {{
      count
      rows {{
        target {{
          id
          approvedSymbol
          approvedName
        }}
        score
      }}
    }}
  }}
}}
"""
response = requests.post(API_URL, json={"query":query})
if response.status_code != 200:
    raise Exception("Something went wrong while fetching genes")
else:
    target_genes_response = response.json()
print(target_genes_response)

{'data': {'disease': {'associatedTargets': {'count': 6584, 'rows': [{'target': {'id': 'ENSG00000188906', 'approvedSymbol': 'LRRK2', 'approvedName': 'leucine rich repeat kinase 2'}, 'score': 0.8789207866590859}, {'target': {'id': 'ENSG00000145335', 'approvedSymbol': 'SNCA', 'approvedName': 'synuclein alpha'}, 'score': 0.8585012729359579}, {'target': {'id': 'ENSG00000159363', 'approvedSymbol': 'ATP13A2', 'approvedName': 'ATPase cation transporting 13A2'}, 'score': 0.8525516685262865}, {'target': {'id': 'ENSG00000185345', 'approvedSymbol': 'PRKN', 'approvedName': 'parkin RBR E3 ubiquitin protein ligase'}, 'score': 0.8505122712454569}, {'target': {'id': 'ENSG00000158828', 'approvedSymbol': 'PINK1', 'approvedName': 'PTEN induced kinase 1'}, 'score': 0.8489915009692078}, {'target': {'id': 'ENSG00000116675', 'approvedSymbol': 'DNAJC6', 'approvedName': 'DnaJ heat shock protein family (Hsp40) member C6'}, 'score': 0.813216808888733}, {'target': {'id': 'ENSG00000116288', 'approvedSymbol': 'PARK7', 'approvedName': 'Parkinsonism associated deglycase'}, 'score': 0.8106296934517689}, {'target': {'id': 'ENSG00000100225', 'approvedSymbol': 'FBXO7', 'approvedName': 'F-box protein 7'}, 'score': 0.8055069071068177}, {'target': {'id': 'ENSG00000177628', 'approvedSymbol': 'GBA1', 'approvedName': 'glucosylceramidase beta 1'}, 'score': 0.7745883765325158}, {'target': {'id': 'ENSG00000069329', 'approvedSymbol': 'VPS35', 'approvedName': 'VPS35 retromer complex component'}, 'score': 0.7603277640165709}, {'target': {'id': 'ENSG00000129003', 'approvedSymbol': 'VPS13C', 'approvedName': 'vacuolar protein sorting 13 homolog C'}, 'score': 0.7290264397828915}, {'target': {'id': 'ENSG00000184381', 'approvedSymbol': 'PLA2G6', 'approvedName': 'phospholipase A2 group VI'}, 'score': 0.7136986181655605}, {'target': {'id': 'ENSG00000186868', 'approvedSymbol': 'MAPT', 'approvedName': 'microtubule associated protein tau'}, 'score': 0.703448428046601}, {'target': {'id': 'ENSG00000176884', 'approvedSymbol': 'GRIN1', 'approvedName': 'glutamate ionotropic receptor NMDA type subunit 1'}, 'score': 0.6946616711131379}, {'target': {'id': 'ENSG00000168539', 'approvedSymbol': 'CHRM1', 'approvedName': 'cholinergic receptor muscarinic 1'}, 'score': 0.6666535051584673}, {'target': {'id': 'ENSG00000197746', 'approvedSymbol': 'PSAP', 'approvedName': 'prosaposin'}, 'score': 0.6446043114744441}, {'target': {'id': 'ENSG00000149295', 'approvedSymbol': 'DRD2', 'approvedName': 'dopamine receptor D2'}, 'score': 0.6411067871540276}, {'target': {'id': 'ENSG00000069535', 'approvedSymbol': 'MAOB', 'approvedName': 'monoamine oxidase B'}, 'score': 0.6305276445019015}, {'target': {'id': 'ENSG00000151577', 'approvedSymbol': 'DRD3', 'approvedName': 'dopamine receptor D3'}, 'score': 0.6297451556796023}, {'target': {'id': 'ENSG00000183454', 'approvedSymbol': 'GRIN2A', 'approvedName': 'glutamate ionotropic receptor NMDA type subunit 2A'}, 'score': 0.626672904226515}, {'target': {'id': 'ENSG00000093010', 'approvedSymbol': 'COMT', 'approvedName': 'catechol-O-methyltransferase'}, 'score': 0.6261522431406615}, {'target': {'id': 'ENSG00000273079', 'approvedSymbol': 'GRIN2B', 'approvedName': 'glutamate ionotropic receptor NMDA type subunit 2B'}, 'score': 0.6258871233729315}, {'target': {'id': 'ENSG00000132437', 'approvedSymbol': 'DDC', 'approvedName': 'dopa decarboxylase'}, 'score': 0.6219588385716877}, {'target': {'id': 'ENSG00000149311', 'approvedSymbol': 'ATM', 'approvedName': 'ATM serine/threonine kinase'}, 'score': 0.6186168553243682}, {'target': {'id': 'ENSG00000069696', 'approvedSymbol': 'DRD4', 'approvedName': 'dopamine receptor D4'}, 'score': 0.6127606392838968}, {'target': {'id': 'ENSG00000127419', 'approvedSymbol': 'TMEM175', 'approvedName': 'transmembrane protein 175'}, 'score': 0.6106957271759151}, {'target': {'id': 'ENSG00000087085', 'approvedSymbol': 'ACHE', 'approvedName': 'acetylcholinesterase (Yt blood group)'}, 'score': 0.6100994576996169}, {'target': {'id': 'ENSG00000161509', 'approvedSymbol': 'GRIN2C', 'approvedName': 'glutamate ionotropic receptor NMDA type subunit 2C'}, 'score': 0.6078815831347348}, {'target': {'id': 'ENSG00000105464', 'approvedSymbol': 'GRIN2D', 'approvedName': 'glutamate ionotropic receptor NMDA type subunit 2D'}, 'score': 0.6076731550593693}, {'target': {'id': 'ENSG00000198785', 'approvedSymbol': 'GRIN3A', 'approvedName': 'glutamate ionotropic receptor NMDA type subunit 3A'}, 'score': 0.6039804624463964}, {'target': {'id': 'ENSG00000116032', 'approvedSymbol': 'GRIN3B', 'approvedName': 'glutamate ionotropic receptor NMDA type subunit 3B'}, 'score': 0.6039804624463964}, {'target': {'id': 'ENSG00000114867', 'approvedSymbol': 'EIF4G1', 'approvedName': 'eukaryotic translation initiation factor 4 gamma 1'}, 'score': 0.6028540412279554}, {'target': {'id': 'ENSG00000114200', 'approvedSymbol': 'BCHE', 'approvedName': 'butyrylcholinesterase'}, 'score': 0.5997926969833182}, {'target': {'id': 'ENSG00000128271', 'approvedSymbol': 'ADORA2A', 'approvedName': 'adenosine A2a receptor'}, 'score': 0.5930864272800089}, {'target': {'id': 'ENSG00000143772', 'approvedSymbol': 'ITPKB', 'approvedName': 'inositol-trisphosphate 3-kinase B'}, 'score': 0.5913437212768456}, {'target': {'id': 'ENSG00000184845', 'approvedSymbol': 'DRD1', 'approvedName': 'dopamine receptor D1'}, 'score': 0.5912739918174205}, {'target': {'id': 'ENSG00000106153', 'approvedSymbol': 'CHCHD2', 'approvedName': 'coiled-coil-helix-coiled-coil-helix domain containing 2'}, 'score': 0.5862152807337631}, {'target': {'id': 'ENSG00000139618', 'approvedSymbol': 'BRCA2', 'approvedName': 'BRCA2 DNA repair associated'}, 'score': 0.577933468659559}, {'target': {'id': 'ENSG00000138246', 'approvedSymbol': 'DNAJC13', 'approvedName': 'DnaJ heat shock protein family (Hsp40) member C13'}, 'score': 0.562777036964892}, {'target': {'id': 'ENSG00000178127', 'approvedSymbol': 'NDUFV2', 'approvedName': 'NADH:ubiquinone oxidoreductase core subunit V2'}, 'score': 0.5619537362393321}, {'target': {'id': 'ENSG00000152214', 'approvedSymbol': 'RIT2', 'approvedName': 'Ras like without CAAX 2'}, 'score': 0.5607013849006937}, {'target': {'id': 'ENSG00000109743', 'approvedSymbol': 'BST1', 'approvedName': 'bone marrow stromal cell antigen 1'}, 'score': 0.5584125097396987}, {'target': {'id': 'ENSG00000198648', 'approvedSymbol': 'STK39', 'approvedName': 'serine/threonine kinase 39'}, 'score': 0.5550487165251987}, {'target': {'id': 'ENSG00000119383', 'approvedSymbol': 'PTPA', 'approvedName': 'protein phosphatase 2 phosphatase activator'}, 'score': 0.5542943442438528}, {'target': {'id': 'ENSG00000102468', 'approvedSymbol': 'HTR2A', 'approvedName': '5-hydroxytryptamine receptor 2A'}, 'score': 0.5521922894969273}, {'target': {'id': 'ENSG00000166311', 'approvedSymbol': 'SMPD1', 'approvedName': 'sphingomyelin phosphodiesterase 1'}, 'score': 0.546300867154792}, {'target': {'id': 'ENSG00000119421', 'approvedSymbol': 'NDUFA8', 'approvedName': 'NADH:ubiquinone oxidoreductase subunit A8'}, 'score': 0.5448223024476979}, {'target': {'id': 'ENSG00000168653', 'approvedSymbol': 'NDUFS5', 'approvedName': 'NADH:ubiquinone oxidoreductase subunit S5'}, 'score': 0.5444313827122621}, {'target': {'id': 'ENSG00000082701', 'approvedSymbol': 'GSK3B', 'approvedName': 'glycogen synthase kinase 3 beta'}, 'score': 0.5425600867755798}, {'target': {'id': 'ENSG00000023228', 'approvedSymbol': 'NDUFS1', 'approvedName': 'NADH:ubiquinone oxidoreductase core subunit S1'}, 'score': 0.5420537685063537}, {'target': {'id': 'ENSG00000124762', 'approvedSymbol': 'CDKN1A', 'approvedName': 'cyclin dependent kinase inhibitor 1A'}, 'score': 0.540342943941515}, {'target': {'id': 'ENSG00000133019', 'approvedSymbol': 'CHRM3', 'approvedName': 'cholinergic receptor muscarinic 3'}, 'score': 0.5382769278533346}, {'target': {'id': 'ENSG00000107295', 'approvedSymbol': 'SH3GL2', 'approvedName': 'SH3 domain containing GRB2 like 2, endophilin A1'}, 'score': 0.5381198873852628}, {'target': {'id': 'ENSG00000163513', 'approvedSymbol': 'TGFBR2', 'approvedName': 'transforming growth factor beta receptor 2'}, 'score': 0.5345838538399322}, {'target': {'id': 'ENSG00000167601', 'approvedSymbol': 'AXL', 'approvedName': 'AXL receptor tyrosine kinase'}, 'score': 0.5277414508359493}, {'target': {'id': 'ENSG00000158864', 'approvedSymbol': 'NDUFS2', 'approvedName': 'NADH:ubiquinone oxidoreductase core subunit S2'}, 'score': 0.5276265338497977}, {'target': {'id': 'ENSG00000135446', 'approvedSymbol': 'CDK4', 'approvedName': 'cyclin dependent kinase 4'}, 'score': 0.5273391220996966}, {'target': {'id': 'ENSG00000166851', 'approvedSymbol': 'PLK1', 'approvedName': 'polo like kinase 1'}, 'score': 0.5272415940824882}, {'target': {'id': 'ENSG00000181072', 'approvedSymbol': 'CHRM2', 'approvedName': 'cholinergic receptor muscarinic 2'}, 'score': 0.5267847523176696}, {'target': {'id': 'ENSG00000178999', 'approvedSymbol': 'AURKB', 'approvedName': 'aurora kinase B'}, 'score': 0.5261379875719714}, {'target': {'id': 'ENSG00000164167', 'approvedSymbol': 'LSM6', 'approvedName': 'LSM6 homolog, U6 small nuclear RNA and mRNA degradation associated'}, 'score': 0.5261379875719714}, {'target': {'id': 'ENSG00000178950', 'approvedSymbol': 'GAK', 'approvedName': 'cyclin G associated kinase'}, 'score': 0.5250222529394727}, {'target': {'id': 'ENSG00000058729', 'approvedSymbol': 'RIOK2', 'approvedName': 'RIO kinase 2'}, 'score': 0.5244154453403582}, {'target': {'id': 'ENSG00000129757', 'approvedSymbol': 'CDKN1C', 'approvedName': 'cyclin dependent kinase inhibitor 1C'}, 'score': 0.5238109398045453}, {'target': {'id': 'ENSG00000012048', 'approvedSymbol': 'BRCA1', 'approvedName': 'BRCA1 DNA repair associated'}, 'score': 0.5232795726356818}, {'target': {'id': 'ENSG00000113161', 'approvedSymbol': 'HMGCR', 'approvedName': '3-hydroxy-3-methylglutaryl-CoA reductase'}, 'score': 0.520264628541555}, {'target': {'id': 'ENSG00000139180', 'approvedSymbol': 'NDUFA9', 'approvedName': 'NADH:ubiquinone oxidoreductase subunit A9'}, 'score': 0.519568922571362}, {'target': {'id': 'ENSG00000147416', 'approvedSymbol': 'ATP6V1B2', 'approvedName': 'ATPase H+ transporting V1 subunit B2'}, 'score': 0.5174172760263839}, {'target': {'id': 'ENSG00000130787', 'approvedSymbol': 'HIP1R', 'approvedName': 'huntingtin interacting protein 1 related'}, 'score': 0.515887618389904}, {'target': {'id': 'ENSG00000170312', 'approvedSymbol': 'CDK1', 'approvedName': 'cyclin dependent kinase 1'}, 'score': 0.5145351345814876}, {'target': {'id': 'ENSG00000004779', 'approvedSymbol': 'NDUFAB1', 'approvedName': 'NADH:ubiquinone oxidoreductase subunit AB1'}, 'score': 0.513598766293333}, {'target': {'id': 'ENSG00000099795', 'approvedSymbol': 'NDUFB7', 'approvedName': 'NADH:ubiquinone oxidoreductase subunit B7'}, 'score': 0.5131330934334296}, {'target': {'id': 'ENSG00000115317', 'approvedSymbol': 'HTRA2', 'approvedName': 'HtrA serine peptidase 2'}, 'score': 0.5102447041332362}, {'target': {'id': 'ENSG00000154277', 'approvedSymbol': 'UCHL1', 'approvedName': 'ubiquitin C-terminal hydrolase L1'}, 'score': 0.5096110790437187}, {'target': {'id': 'ENSG00000136235', 'approvedSymbol': 'GPNMB', 'approvedName': 'glycoprotein nmb'}, 'score': 0.509149611050944}, {'target': {'id': 'ENSG00000010256', 'approvedSymbol': 'UQCRC1', 'approvedName': 'ubiquinol-cytochrome c reductase core protein 1'}, 'score': 0.5081909374303535}, {'target': {'id': 'ENSG00000101224', 'approvedSymbol': 'CDC25B', 'approvedName': 'cell division cycle 25B'}, 'score': 0.5049953710005523}, {'target': {'id': 'ENSG00000131408', 'approvedSymbol': 'NR1H2', 'approvedName': 'nuclear receptor subfamily 1 group H member 2'}, 'score': 0.503643440242305}, {'target': {'id': 'ENSG00000288636', 'approvedSymbol': 'ENSG00000288636', 'approvedName': 'novel  protein'}, 'score': 0.5035336938353238}, {'target': {'id': 'ENSG00000023516', 'approvedSymbol': 'AKAP11', 'approvedName': 'A-kinase anchoring protein 11'}, 'score': 0.5030534368197492}, {'target': {'id': 'ENSG00000198563', 'approvedSymbol': 'DDX39B', 'approvedName': 'DExD-box helicase 39B'}, 'score': 0.5030392466541774}, {'target': {'id': 'ENSG00000120539', 'approvedSymbol': 'MASTL', 'approvedName': 'microtubule associated serine/threonine kinase like'}, 'score': 0.5030392466541774}, {'target': {'id': 'ENSG00000100330', 'approvedSymbol': 'MTMR3', 'approvedName': 'myotubularin related protein 3'}, 'score': 0.5030392466541774}, {'target': {'id': 'ENSG00000143374', 'approvedSymbol': 'TARS2', 'approvedName': 'threonyl-tRNA synthetase 2, mitochondrial'}, 'score': 0.5030392466541774}, {'target': {'id': 'ENSG00000147889', 'approvedSymbol': 'CDKN2A', 'approvedName': 'cyclin dependent kinase inhibitor 2A'}, 'score': 0.5028580562800856}, {'target': {'id': 'ENSG00000115020', 'approvedSymbol': 'PIKFYVE', 'approvedName': 'phosphoinositide kinase, FYVE-type zinc finger containing'}, 'score': 0.5015419169371306}, {'target': {'id': 'ENSG00000155097', 'approvedSymbol': 'ATP6V1C1', 'approvedName': 'ATPase H+ transporting V1 subunit C1'}, 'score': 0.5014761923729811}, {'target': {'id': 'ENSG00000167258', 'approvedSymbol': 'CDK12', 'approvedName': 'cyclin dependent kinase 12'}, 'score': 0.5012604633931973}, {'target': {'id': 'ENSG00000103546', 'approvedSymbol': 'SLC6A2', 'approvedName': 'solute carrier family 6 member 2'}, 'score': 0.4998189024649898}, {'target': {'id': 'ENSG00000143393', 'approvedSymbol': 'PI4KB', 'approvedName': 'phosphatidylinositol 4-kinase beta'}, 'score': 0.499342162977125}, {'target': {'id': 'ENSG00000147883', 'approvedSymbol': 'CDKN2B', 'approvedName': 'cyclin dependent kinase inhibitor 2B'}, 'score': 0.4986317283239781}, {'target': {'id': 'ENSG00000087586', 'approvedSymbol': 'AURKA', 'approvedName': 'aurora kinase A'}, 'score': 0.4985026490371032}, {'target': {'id': 'ENSG00000153234', 'approvedSymbol': 'NR4A2', 'approvedName': 'nuclear receptor subfamily 4 group A member 2'}, 'score': 0.4983493331910446}, {'target': {'id': 'ENSG00000114573', 'approvedSymbol': 'ATP6V1A', 'approvedName': 'ATPase H+ transporting V1 subunit A'}, 'score': 0.4980865060822472}, {'target': {'id': 'ENSG00000139505', 'approvedSymbol': 'MTMR6', 'approvedName': 'myotubularin related protein 6'}, 'score': 0.4976720718834108}, {'target': {'id': 'ENSG00000010810', 'approvedSymbol': 'FYN', 'approvedName': 'FYN proto-oncogene, Src family tyrosine kinase'}, 'score': 0.49753184868598904}, {'target': {'id': 'ENSG00000113712', 'approvedSymbol': 'CSNK1A1', 'approvedName': 'casein kinase 1 alpha 1'}, 'score': 0.4972180011438692}, {'target': {'id': 'ENSG00000169676', 'approvedSymbol': 'DRD5', 'approvedName': 'dopamine receptor D5'}, 'score': 0.496620031338111}, {'target': {'id': 'ENSG00000164615', 'approvedSymbol': 'CAMLG', 'approvedName': 'calcium modulating ligand'}, 'score': 0.49420155075608413}, {'target': {'id': 'ENSG00000094755', 'approvedSymbol': 'GABRP', 'approvedName': 'gamma-aminobutyric acid type A receptor subunit pi'}, 'score': 0.49140257010229677}]}}}}

In [4]:
def get_target_genes(response:dict) -> dict:
    target_res = response['data']['disease']['associatedTargets']['rows']
    genes = []
    for i in target_res:
        gene_data = {
            "gene_id": i['target']['id'],
            "symbol":  i['target']['approvedSymbol'],
            "name": i['target']['approvedName'],
            "score": i['score']
        }
        genes.append(gene_data)
    return genes

genes_target = get_target_genes(target_genes_response)
print(genes_target)

[{'gene_id': 'ENSG00000188906', 'symbol': 'LRRK2', 'name': 'leucine rich repeat kinase 2', 'score': 0.8789207866590859}, {'gene_id': 'ENSG00000145335', 'symbol': 'SNCA', 'name': 'synuclein alpha', 'score': 0.8585012729359579}, {'gene_id': 'ENSG00000159363', 'symbol': 'ATP13A2', 'name': 'ATPase cation transporting 13A2', 'score': 0.8525516685262865}, {'gene_id': 'ENSG00000185345', 'symbol': 'PRKN', 'name': 'parkin RBR E3 ubiquitin protein ligase', 'score': 0.8505122712454569}, {'gene_id': 'ENSG00000158828', 'symbol': 'PINK1', 'name': 'PTEN induced kinase 1', 'score': 0.8489915009692078}, {'gene_id': 'ENSG00000116675', 'symbol': 'DNAJC6', 'name': 'DnaJ heat shock protein family (Hsp40) member C6', 'score': 0.813216808888733}, {'gene_id': 'ENSG00000116288', 'symbol': 'PARK7', 'name': 'Parkinsonism associated deglycase', 'score': 0.8106296934517689}, {'gene_id': 'ENSG00000100225', 'symbol': 'FBXO7', 'name': 'F-box protein 7', 'score': 0.8055069071068177}, {'gene_id': 'ENSG00000177628', 'symbol': 'GBA1', 'name': 'glucosylceramidase beta 1', 'score': 0.7745883765325158}, {'gene_id': 'ENSG00000069329', 'symbol': 'VPS35', 'name': 'VPS35 retromer complex component', 'score': 0.7603277640165709}, {'gene_id': 'ENSG00000129003', 'symbol': 'VPS13C', 'name': 'vacuolar protein sorting 13 homolog C', 'score': 0.7290264397828915}, {'gene_id': 'ENSG00000184381', 'symbol': 'PLA2G6', 'name': 'phospholipase A2 group VI', 'score': 0.7136986181655605}, {'gene_id': 'ENSG00000186868', 'symbol': 'MAPT', 'name': 'microtubule associated protein tau', 'score': 0.703448428046601}, {'gene_id': 'ENSG00000176884', 'symbol': 'GRIN1', 'name': 'glutamate ionotropic receptor NMDA type subunit 1', 'score': 0.6946616711131379}, {'gene_id': 'ENSG00000168539', 'symbol': 'CHRM1', 'name': 'cholinergic receptor muscarinic 1', 'score': 0.6666535051584673}, {'gene_id': 'ENSG00000197746', 'symbol': 'PSAP', 'name': 'prosaposin', 'score': 0.6446043114744441}, {'gene_id': 'ENSG00000149295', 'symbol': 'DRD2', 'name': 'dopamine receptor D2', 'score': 0.6411067871540276}, {'gene_id': 'ENSG00000069535', 'symbol': 'MAOB', 'name': 'monoamine oxidase B', 'score': 0.6305276445019015}, {'gene_id': 'ENSG00000151577', 'symbol': 'DRD3', 'name': 'dopamine receptor D3', 'score': 0.6297451556796023}, {'gene_id': 'ENSG00000183454', 'symbol': 'GRIN2A', 'name': 'glutamate ionotropic receptor NMDA type subunit 2A', 'score': 0.626672904226515}, {'gene_id': 'ENSG00000093010', 'symbol': 'COMT', 'name': 'catechol-O-methyltransferase', 'score': 0.6261522431406615}, {'gene_id': 'ENSG00000273079', 'symbol': 'GRIN2B', 'name': 'glutamate ionotropic receptor NMDA type subunit 2B', 'score': 0.6258871233729315}, {'gene_id': 'ENSG00000132437', 'symbol': 'DDC', 'name': 'dopa decarboxylase', 'score': 0.6219588385716877}, {'gene_id': 'ENSG00000149311', 'symbol': 'ATM', 'name': 'ATM serine/threonine kinase', 'score': 0.6186168553243682}, {'gene_id': 'ENSG00000069696', 'symbol': 'DRD4', 'name': 'dopamine receptor D4', 'score': 0.6127606392838968}, {'gene_id': 'ENSG00000127419', 'symbol': 'TMEM175', 'name': 'transmembrane protein 175', 'score': 0.6106957271759151}, {'gene_id': 'ENSG00000087085', 'symbol': 'ACHE', 'name': 'acetylcholinesterase (Yt blood group)', 'score': 0.6100994576996169}, {'gene_id': 'ENSG00000161509', 'symbol': 'GRIN2C', 'name': 'glutamate ionotropic receptor NMDA type subunit 2C', 'score': 0.6078815831347348}, {'gene_id': 'ENSG00000105464', 'symbol': 'GRIN2D', 'name': 'glutamate ionotropic receptor NMDA type subunit 2D', 'score': 0.6076731550593693}, {'gene_id': 'ENSG00000198785', 'symbol': 'GRIN3A', 'name': 'glutamate ionotropic receptor NMDA type subunit 3A', 'score': 0.6039804624463964}, {'gene_id': 'ENSG00000116032', 'symbol': 'GRIN3B', 'name': 'glutamate ionotropic receptor NMDA type subunit 3B', 'score': 0.6039804624463964}, {'gene_id': 'ENSG00000114867', 'symbol': 'EIF4G1', 'name': 'eukaryotic translation initiation factor 4 gamma 1', 'score': 0.6028540412279554}, {'gene_id': 'ENSG00000114200', 'symbol': 'BCHE', 'name': 'butyrylcholinesterase', 'score': 0.5997926969833182}, {'gene_id': 'ENSG00000128271', 'symbol': 'ADORA2A', 'name': 'adenosine A2a receptor', 'score': 0.5930864272800089}, {'gene_id': 'ENSG00000143772', 'symbol': 'ITPKB', 'name': 'inositol-trisphosphate 3-kinase B', 'score': 0.5913437212768456}, {'gene_id': 'ENSG00000184845', 'symbol': 'DRD1', 'name': 'dopamine receptor D1', 'score': 0.5912739918174205}, {'gene_id': 'ENSG00000106153', 'symbol': 'CHCHD2', 'name': 'coiled-coil-helix-coiled-coil-helix domain containing 2', 'score': 0.5862152807337631}, {'gene_id': 'ENSG00000139618', 'symbol': 'BRCA2', 'name': 'BRCA2 DNA repair associated', 'score': 0.577933468659559}, {'gene_id': 'ENSG00000138246', 'symbol': 'DNAJC13', 'name': 'DnaJ heat shock protein family (Hsp40) member C13', 'score': 0.562777036964892}, {'gene_id': 'ENSG00000178127', 'symbol': 'NDUFV2', 'name': 'NADH:ubiquinone oxidoreductase core subunit V2', 'score': 0.5619537362393321}, {'gene_id': 'ENSG00000152214', 'symbol': 'RIT2', 'name': 'Ras like without CAAX 2', 'score': 0.5607013849006937}, {'gene_id': 'ENSG00000109743', 'symbol': 'BST1', 'name': 'bone marrow stromal cell antigen 1', 'score': 0.5584125097396987}, {'gene_id': 'ENSG00000198648', 'symbol': 'STK39', 'name': 'serine/threonine kinase 39', 'score': 0.5550487165251987}, {'gene_id': 'ENSG00000119383', 'symbol': 'PTPA', 'name': 'protein phosphatase 2 phosphatase activator', 'score': 0.5542943442438528}, {'gene_id': 'ENSG00000102468', 'symbol': 'HTR2A', 'name': '5-hydroxytryptamine receptor 2A', 'score': 0.5521922894969273}, {'gene_id': 'ENSG00000166311', 'symbol': 'SMPD1', 'name': 'sphingomyelin phosphodiesterase 1', 'score': 0.546300867154792}, {'gene_id': 'ENSG00000119421', 'symbol': 'NDUFA8', 'name': 'NADH:ubiquinone oxidoreductase subunit A8', 'score': 0.5448223024476979}, {'gene_id': 'ENSG00000168653', 'symbol': 'NDUFS5', 'name': 'NADH:ubiquinone oxidoreductase subunit S5', 'score': 0.5444313827122621}, {'gene_id': 'ENSG00000082701', 'symbol': 'GSK3B', 'name': 'glycogen synthase kinase 3 beta', 'score': 0.5425600867755798}, {'gene_id': 'ENSG00000023228', 'symbol': 'NDUFS1', 'name': 'NADH:ubiquinone oxidoreductase core subunit S1', 'score': 0.5420537685063537}, {'gene_id': 'ENSG00000124762', 'symbol': 'CDKN1A', 'name': 'cyclin dependent kinase inhibitor 1A', 'score': 0.540342943941515}, {'gene_id': 'ENSG00000133019', 'symbol': 'CHRM3', 'name': 'cholinergic receptor muscarinic 3', 'score': 0.5382769278533346}, {'gene_id': 'ENSG00000107295', 'symbol': 'SH3GL2', 'name': 'SH3 domain containing GRB2 like 2, endophilin A1', 'score': 0.5381198873852628}, {'gene_id': 'ENSG00000163513', 'symbol': 'TGFBR2', 'name': 'transforming growth factor beta receptor 2', 'score': 0.5345838538399322}, {'gene_id': 'ENSG00000167601', 'symbol': 'AXL', 'name': 'AXL receptor tyrosine kinase', 'score': 0.5277414508359493}, {'gene_id': 'ENSG00000158864', 'symbol': 'NDUFS2', 'name': 'NADH:ubiquinone oxidoreductase core subunit S2', 'score': 0.5276265338497977}, {'gene_id': 'ENSG00000135446', 'symbol': 'CDK4', 'name': 'cyclin dependent kinase 4', 'score': 0.5273391220996966}, {'gene_id': 'ENSG00000166851', 'symbol': 'PLK1', 'name': 'polo like kinase 1', 'score': 0.5272415940824882}, {'gene_id': 'ENSG00000181072', 'symbol': 'CHRM2', 'name': 'cholinergic receptor muscarinic 2', 'score': 0.5267847523176696}, {'gene_id': 'ENSG00000178999', 'symbol': 'AURKB', 'name': 'aurora kinase B', 'score': 0.5261379875719714}, {'gene_id': 'ENSG00000164167', 'symbol': 'LSM6', 'name': 'LSM6 homolog, U6 small nuclear RNA and mRNA degradation associated', 'score': 0.5261379875719714}, {'gene_id': 'ENSG00000178950', 'symbol': 'GAK', 'name': 'cyclin G associated kinase', 'score': 0.5250222529394727}, {'gene_id': 'ENSG00000058729', 'symbol': 'RIOK2', 'name': 'RIO kinase 2', 'score': 0.5244154453403582}, {'gene_id': 'ENSG00000129757', 'symbol': 'CDKN1C', 'name': 'cyclin dependent kinase inhibitor 1C', 'score': 0.5238109398045453}, {'gene_id': 'ENSG00000012048', 'symbol': 'BRCA1', 'name': 'BRCA1 DNA repair associated', 'score': 0.5232795726356818}, {'gene_id': 'ENSG00000113161', 'symbol': 'HMGCR', 'name': '3-hydroxy-3-methylglutaryl-CoA reductase', 'score': 0.520264628541555}, {'gene_id': 'ENSG00000139180', 'symbol': 'NDUFA9', 'name': 'NADH:ubiquinone oxidoreductase subunit A9', 'score': 0.519568922571362}, {'gene_id': 'ENSG00000147416', 'symbol': 'ATP6V1B2', 'name': 'ATPase H+ transporting V1 subunit B2', 'score': 0.5174172760263839}, {'gene_id': 'ENSG00000130787', 'symbol': 'HIP1R', 'name': 'huntingtin interacting protein 1 related', 'score': 0.515887618389904}, {'gene_id': 'ENSG00000170312', 'symbol': 'CDK1', 'name': 'cyclin dependent kinase 1', 'score': 0.5145351345814876}, {'gene_id': 'ENSG00000004779', 'symbol': 'NDUFAB1', 'name': 'NADH:ubiquinone oxidoreductase subunit AB1', 'score': 0.513598766293333}, {'gene_id': 'ENSG00000099795', 'symbol': 'NDUFB7', 'name': 'NADH:ubiquinone oxidoreductase subunit B7', 'score': 0.5131330934334296}, {'gene_id': 'ENSG00000115317', 'symbol': 'HTRA2', 'name': 'HtrA serine peptidase 2', 'score': 0.5102447041332362}, {'gene_id': 'ENSG00000154277', 'symbol': 'UCHL1', 'name': 'ubiquitin C-terminal hydrolase L1', 'score': 0.5096110790437187}, {'gene_id': 'ENSG00000136235', 'symbol': 'GPNMB', 'name': 'glycoprotein nmb', 'score': 0.509149611050944}, {'gene_id': 'ENSG00000010256', 'symbol': 'UQCRC1', 'name': 'ubiquinol-cytochrome c reductase core protein 1', 'score': 0.5081909374303535}, {'gene_id': 'ENSG00000101224', 'symbol': 'CDC25B', 'name': 'cell division cycle 25B', 'score': 0.5049953710005523}, {'gene_id': 'ENSG00000131408', 'symbol': 'NR1H2', 'name': 'nuclear receptor subfamily 1 group H member 2', 'score': 0.503643440242305}, {'gene_id': 'ENSG00000288636', 'symbol': 'ENSG00000288636', 'name': 'novel  protein', 'score': 0.5035336938353238}, {'gene_id': 'ENSG00000023516', 'symbol': 'AKAP11', 'name': 'A-kinase anchoring protein 11', 'score': 0.5030534368197492}, {'gene_id': 'ENSG00000198563', 'symbol': 'DDX39B', 'name': 'DExD-box helicase 39B', 'score': 0.5030392466541774}, {'gene_id': 'ENSG00000120539', 'symbol': 'MASTL', 'name': 'microtubule associated serine/threonine kinase like', 'score': 0.5030392466541774}, {'gene_id': 'ENSG00000100330', 'symbol': 'MTMR3', 'name': 'myotubularin related protein 3', 'score': 0.5030392466541774}, {'gene_id': 'ENSG00000143374', 'symbol': 'TARS2', 'name': 'threonyl-tRNA synthetase 2, mitochondrial', 'score': 0.5030392466541774}, {'gene_id': 'ENSG00000147889', 'symbol': 'CDKN2A', 'name': 'cyclin dependent kinase inhibitor 2A', 'score': 0.5028580562800856}, {'gene_id': 'ENSG00000115020', 'symbol': 'PIKFYVE', 'name': 'phosphoinositide kinase, FYVE-type zinc finger containing', 'score': 0.5015419169371306}, {'gene_id': 'ENSG00000155097', 'symbol': 'ATP6V1C1', 'name': 'ATPase H+ transporting V1 subunit C1', 'score': 0.5014761923729811}, {'gene_id': 'ENSG00000167258', 'symbol': 'CDK12', 'name': 'cyclin dependent kinase 12', 'score': 0.5012604633931973}, {'gene_id': 'ENSG00000103546', 'symbol': 'SLC6A2', 'name': 'solute carrier family 6 member 2', 'score': 0.4998189024649898}, {'gene_id': 'ENSG00000143393', 'symbol': 'PI4KB', 'name': 'phosphatidylinositol 4-kinase beta', 'score': 0.499342162977125}, {'gene_id': 'ENSG00000147883', 'symbol': 'CDKN2B', 'name': 'cyclin dependent kinase inhibitor 2B', 'score': 0.4986317283239781}, {'gene_id': 'ENSG00000087586', 'symbol': 'AURKA', 'name': 'aurora kinase A', 'score': 0.4985026490371032}, {'gene_id': 'ENSG00000153234', 'symbol': 'NR4A2', 'name': 'nuclear receptor subfamily 4 group A member 2', 'score': 0.4983493331910446}, {'gene_id': 'ENSG00000114573', 'symbol': 'ATP6V1A', 'name': 'ATPase H+ transporting V1 subunit A', 'score': 0.4980865060822472}, {'gene_id': 'ENSG00000139505', 'symbol': 'MTMR6', 'name': 'myotubularin related protein 6', 'score': 0.4976720718834108}, {'gene_id': 'ENSG00000010810', 'symbol': 'FYN', 'name': 'FYN proto-oncogene, Src family tyrosine kinase', 'score': 0.49753184868598904}, {'gene_id': 'ENSG00000113712', 'symbol': 'CSNK1A1', 'name': 'casein kinase 1 alpha 1', 'score': 0.4972180011438692}, {'gene_id': 'ENSG00000169676', 'symbol': 'DRD5', 'name': 'dopamine receptor D5', 'score': 0.496620031338111}, {'gene_id': 'ENSG00000164615', 'symbol': 'CAMLG', 'name': 'calcium modulating ligand', 'score': 0.49420155075608413}, {'gene_id': 'ENSG00000094755', 'symbol': 'GABRP', 'name': 'gamma-aminobutyric acid type A receptor subunit pi', 'score': 0.49140257010229677}]

In [5]:
genes_target_prelim_df = pd.DataFrame(genes_target)
genes_target_prelim_df

,gene_id,symbol,name,score
0,ENSG00000188906,LRRK2,leucine rich repeat kinase 2,0.878921
1,ENSG00000145335,SNCA,synuclein alpha,0.858501
2,ENSG00000159363,ATP13A2,ATPase cation transporting 13A2,0.852552
3,ENSG00000185345,PRKN,parkin RBR E3 ubiquitin protein ligase,0.850512
4,ENSG00000158828,PINK1,PTEN induced kinase 1,0.848992
...,...,...,...,...
95,ENSG00000010810,FYN,"FYN proto-oncogene, Src family tyrosine kinase",0.497532
96,ENSG00000113712,CSNK1A1,casein kinase 1 alpha 1,0.497218
97,ENSG00000169676,DRD5,dopamine receptor D5,0.496620
98,ENSG00000164615,CAMLG,calcium modulating ligand,0.494202
99,ENSG00000094755,GABRP,gamma-aminobutyric acid type A receptor subuni...,0.491403

In [6]:
def load_gtex_expression(filepath: str):
    df = pd.read_csv(filepath, sep="\t", skiprows=2, compression='gzip')
    brain_cols = [col for col in df.columns if 'Brain' in col]
    df["median_tpm_brain"] = df[brain_cols].median(axis=1)
    df = df.rename(columns={"Name": "gene_id", "Description": "symbol"})
    df["gene_id_stripped"] = df["gene_id"].str.split(".").str[0]
    return df[["gene_id_stripped", "symbol", "median_tpm_brain"]]

gene_tpm_brain_df = load_gtex_expression("GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_median_tpm (1).gct.gz")

def merge_open_targets_gtex(df_1, df_2):
    merged_df = df_1.merge(
        df_2,
        left_on="gene_id",
        right_on="gene_id_stripped",
        how="left"
    )
    merged_df = merged_df.drop(columns=["gene_id_stripped"])
    return merged_df

mereged_genes_parkinsons = merge_open_targets_gtex(genes_target_prelim_df, gene_tpm_brain_df)

In [7]:
mereged_genes_parkinsons
def prioritize_genes(df):
    new_df = df.copy()
    new_df["median_tpm_brain"] = new_df["median_tpm_brain"].fillna(0)
    new_df["final_score"] =  np.log2(1+new_df["median_tpm_brain"]) * new_df["score"]
    new_df = new_df.sort_values(by="final_score", ascending=False)
    return new_df

final_genes_parkinsons_sorted = prioritize_genes(mereged_genes_parkinsons)

In [8]:
final_genes_parkinsons_sorted

,gene_id,symbol_x,name,score,symbol_y,median_tpm_brain,final_score
6,ENSG00000116288,PARK7,Parkinsonism associated deglycase,0.810630,PARK7,182.992000,6.098772
15,ENSG00000197746,PSAP,prosaposin,0.644604,PSAP,633.102000,6.000345
2,ENSG00000159363,ATP13A2,ATPase cation transporting 13A2,0.852552,ATP13A2,59.661500,5.049416
36,ENSG00000106153,CHCHD2,coiled-coil-helix-coiled-coil-helix domain con...,0.586215,CHCHD2,322.936000,4.888780
47,ENSG00000168653,NDUFS5,NADH:ubiquinone oxidoreductase subunit S5,0.544431,NDUFS5,428.624000,4.762104
...,...,...,...,...,...,...,...
59,ENSG00000178999,AURKB,aurora kinase B,0.526138,AURKB,0.053693,0.039700
18,ENSG00000151577,DRD3,dopamine receptor D3,0.629745,DRD3,0.011972,0.010812
99,ENSG00000094755,GABRP,gamma-aminobutyric acid type A receptor subuni...,0.491403,GABRP,0.015352,0.010801
88,ENSG00000103546,SLC6A2,solute carrier family 6 member 2,0.499819,SLC6A2,0.007738,0.005558
78,ENSG00000288636,ENSG00000288636,novel protein,0.503534,NaN,0.000000,0.000000

In [9]:
def run_gprofiler(symbols: list):
    gp = GProfiler(return_dataframe=True)
    results = gp.profile(organism='hsapiens', query=symbols, no_evidences=False)
    return results

gprofiler_res = run_gprofiler(final_genes_parkinsons_sorted.head(50)['symbol_x'].dropna().tolist())

In [10]:
gprofiler_res.to_csv('OUTPUT_CSV.csv', index=False)

In [11]:
def enrich_top_200_genes(gprofiler_top):
    enriched_score = defaultdict(float)
    for _, row in gprofiler_top.iterrows():
        if (len(row["intersections"]) == 0):
            continue
        for i in row["intersections"]:
            enriched_score[i] += -np.log10(row["p_value"])/len(row["intersections"])
    return enriched_score

enriched_score = enrich_top_200_genes(gprofiler_res)

In [12]:
enriched_score

defaultdict(float,
            {'PARK7': np.float64(121.5375532654405),
             'PSAP': np.float64(31.40551603777035),
             'ATP13A2': np.float64(65.1683109253922),
             'CHCHD2': np.float64(36.74917827530963),
             'SNCA': np.float64(126.88162502179861),
             'UCHL1': np.float64(65.59297273493974),
             'FBXO7': np.float64(42.943653448993686),
             'MAPT': np.float64(65.73791684532166),
             'EIF4G1': np.float64(54.17538887267741),
             'VPS35': np.float64(83.74497758722529),
             'UQCRC1': np.float64(50.137011537967325),
             'PTPA': np.float64(20.501792481830638),
             'GBA1': np.float64(72.90899859908062),
             'PLA2G6': np.float64(43.07518869425227),
             'HTRA2': np.float64(57.31597835436296),
             'PINK1': np.float64(118.9841456419906),
             'DNAJC6': np.float64(57.304407678769785),
             'COMT': np.float64(30.716059337324523),
             'ATP6V1A': np.float64(71.27928671946869),
             'SMPD1': np.float64(21.441393286679837),
             'NDUFS5': np.float64(80.41081352468312),
             'NDUFB7': np.float64(74.04741025603654),
             'NDUFA8': np.float64(77.96713234458757),
             'NDUFV2': np.float64(76.89508386355051),
             'NDUFAB1': np.float64(57.432742615810774),
             'NDUFS2': np.float64(82.17703425141009),
             'NDUFS1': np.float64(78.5267560957768),
             'ATP6V1B2': np.float64(55.518058043561474),
             'ITPKB': np.float64(8.503687790692373),
             'SH3GL2': np.float64(21.93908508397886),
             'FYN': np.float64(35.80868026102956),
             'NR1H2': np.float64(16.62665991599972),
             'STK39': np.float64(14.826237594643311),
             'GAK': np.float64(19.527452276924542),
             'CSNK1A1': np.float64(11.806440066544578),
             'PI4KB': np.float64(10.898387662345899),
             'CDC25B': np.float64(3.280237764176361),
             'HMGCR': np.float64(19.887125930934335),
             'CDK4': np.float64(8.492865188201819),
             'GRIN1': np.float64(33.47549254890602),
             'MAOB': np.float64(28.162368945311933),
             'TMEM175': np.float64(14.540193896775323),
             'HIP1R': np.float64(19.479635819489364),
             'DDX39B': np.float64(4.310511676282774),
             'CHRM1': np.float64(16.917448345492126),
             'CAMLG': np.float64(11.41373534711088),
             'GRIN2C': np.float64(21.010422476813805),
             'ACHE': np.float64(14.862522117065026),
             'ATP6V1C1': np.float64(38.28503411476515),
             'AKAP11': np.float64(3.1301012300809914)})

In [13]:
def compute_enriched_score(df_200, g_profiler_scores_dict, alpha):
    df_200_final = df_200.copy()
    df_200_final["g_profiler_scores"] = df_200_final["symbol_x"].map(g_profiler_scores_dict).fillna(0)
    df_200_final["final_gene_score"] = df_200_final["final_score"] + alpha*df_200_final["g_profiler_scores"]
    return df_200_final.sort_values(by="final_gene_score", ascending=False)

final_genes_scored = compute_enriched_score(final_genes_parkinsons_sorted.head(50), enriched_score, 1.0)

In [14]:
final_genes_scored.head(5)

,gene_id,symbol_x,name,score,symbol_y,median_tpm_brain,final_score,g_profiler_scores,final_gene_score
1,ENSG00000145335,SNCA,synuclein alpha,0.858501,SNCA,38.2467,4.545335,126.881625,131.426960
6,ENSG00000116288,PARK7,Parkinsonism associated deglycase,0.810630,PARK7,182.9920,6.098772,121.537553,127.636325
4,ENSG00000158828,PINK1,PTEN induced kinase 1,0.848992,PINK1,41.0024,4.578102,118.984146,123.562247
9,ENSG00000069329,VPS35,VPS35 retromer complex component,0.760328,VPS35,19.3967,3.307626,83.744978,87.052604
47,ENSG00000168653,NDUFS5,NADH:ubiquinone oxidoreductase subunit S5,0.544431,NDUFS5,428.6240,4.762104,80.410814,85.172917

In [15]:
# check literature hits for the genes shortlisted in Workflow 1

def check_eu_pmc(disease: str, gene: str) -> dict:
    url = "https://www.ebi.ac.uk/europepmc/webservices/rest/search"
    try:
        response = requests.get(url, {
            "query": f'"{gene}" AND "{disease}"',
            "format": "json",
            "pageSize": 100
        })
        response.raise_for_status()
        data = response.json()
        hit_count = int(data.get("hitCount", 0))
        res = data.get("resultList", {}).get("result", [])
        years = [int(x["pubYear"]) for x in res if "pubYear" in x]
        fulltext_hits = sum(1 for paper in res if paper.get("hasTextMinedTerms") == "Y")
        return {
            "gene":gene,
            "hit_count":hit_count,
            "fulltext_hits":fulltext_hits,
            "mean_pub_year": np.mean(years) if years else np.nan
        }
    except Exception as e:
        raise RuntimeError(f"Error while fetching from EU PMC: {str(e)}")

In [16]:
def check_literature_match_for_genes(gene_list: list, disease: str) -> dict:
    return [check_eu_pmc(disease, x) for x in gene_list]

genes_lit_match = check_literature_match_for_genes(final_genes_scored["symbol_x"].to_list(), "Parkinson's Disease")
genes_lit_match_df = pd.DataFrame(genes_lit_match)

In [17]:
genes_lit_match_df.head(5)

     gene  hit_count  fulltext_hits  mean_pub_year
0    SNCA       7608             97        2024.86
1   PARK7       2316             98        2024.44
2   PINK1       6453             98        2024.75
3   VPS35       1397            100        2024.27
4  NDUFS5         50             50        2018.24

In [21]:
class LiteratureFetcher:

    def __init__(self, gene_list: List[str], disease_name: str, page_size: int = 20):
        self.gene_list = gene_list
        self.disease_name = disease_name
        self.page_size = page_size
        self._base_url = "https://www.ebi.ac.uk/europepmc/webservices/rest/search"

    def fetch_articles(self) -> List[Dict]:
        gene_wise_articles = []
        for gene in self.gene_list:
            query = f"{gene} AND {self.disease_name}"
            try:
                response = requests.get(self._base_url, params={
                    "query": query,
                    "format": "json",
                    "pageSize": self.page_size
                })
            except Exception as e:
                print(f"Error for gene: {gene} -> {e}")
                continue
            articles = []
            for i in response.json().get("resultList", {}).get("result", []):
                if "pmcid" in i:
                    articles.append({
                        "pmcid": i["pmcid"],
                        "pmid": i.get("pmid", ""),
                        "title": i.get("title", ""),
                        "source": i.get("source", ""),
                        "journal": i.get("journalTitle", "")
                    })
            gene_wise_articles.append({"gene":gene, "articles":articles})
        return gene_wise_articles


fetcher = LiteratureFetcher(final_genes_scored["symbol_x"].to_list(), "Parkinson's Disease")
article_list = fetcher.fetch_articles()